### ISSUE TITLE
populate fa16 index.md pages with content from pages.md

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/fieldnotes-content#33]
Building off of #25.

For each `index.md` under [fa16](https://github.com/cu-mkp/fieldnotes-content/tree/main/content/fa16), take contents of `pages.md` in the same directory and insert in the proper location. This needs to be done recursively within the directory at every level.

# For example, for [fa16](https://github.com/cu-mkp/fieldnotes-content/tree/main/content/fa16):

## `index.md` 

```
---
title: ""
output:
    html_document:
        template: semester.html
semester: "fa17"
fullsemester: "Fall 2017"

intro: ""

pages:
  - title: ""
    link: ""
    desc: ""
---
```

## `pages.md`
```
  - title: "Annotations"
    link: "ann/index.html"
    desc: ""
  - title: "Field Notes"
    link: "fld/index.html"
    desc: ""
  - title: "Profiles"
    link: "profiles/index.html"
    desc: ""
```

## `index.md` after insertion
```
---
title: ""
output:
    html_document:
        template: semester.html
semester: "fa17"
fullsemester: "Fall 2017"

intro: ""

pages:
  - title: "Annotations"
    link: "ann/index.html"
    desc: ""
  - title: "Field Notes"
    link: "fld/index.html"
    desc: ""
  - title: "Profiles"
    link: "profiles/index.html"
    desc: ""
---
```
